[profile.default]
solc-version = "0.8.26"
evm-version = "cancun"
src = "src"
out = "out"
libs = ["lib"]
# remappings = [
    # "eas-contracts/=lib/eas-contracts/",
    # "@openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    # "@openzeppelin-contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
# ]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
